### ISSUE TITLE
Broken with 0.96.0

### ISSUE THREAD

**Issue by juan11perez** [custom-components/camera.combined#10]
camera.combined

config check error:
Integration combined not found when trying to verify its camera platform.

component doesnt load.

**Comment by ludeeus** [comment]
weird.. I should have been broken since 0.92.

**Comment by juan11perez** [comment]
haha, well it wasnt. It would take time to load, but eventually it would. now it RIP

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/camera.combined/releases/tag/0.1.0
